# Generated by Django 5.1.6 on 2025-03-20 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MUser',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('delete_flag', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'm_user_management',
            },
        ),
        migrations.CreateModel(
            name='UserPassword',
            fields=[
                ('user_password_id', models.AutoField(primary_key=True, serialize=False)),
                ('password_hash', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.muser')),
            ],
            options={
                'db_table': 'user_password',
            },
        ),
    ]
