# Generated by Django 5.1.6 on 2025-03-20 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MProductType',
            fields=[
                ('type_id', models.AutoField(primary_key=True, serialize=False)),
                ('type_name', models.CharField(max_length=255)),
                ('delete_flag', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'm_product_type',
            },
        ),
    ]
