# Generated by Django 5.1.6 on 2025-03-21 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_mproducttype'),
    ]

    operations = [
        migrations.CreateModel(
            name='MProduct',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('image', models.CharField(max_length=255)),
                ('quality_inventory', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status_flag', models.BooleanField(default=True)),
                ('display_flag', models.BooleanField(default=True)),
                ('delete_flag', models.BooleanField(default=False)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.mproducttype')),
            ],
            options={
                'db_table': 'm_product',
            },
        ),
    ]
