# Generated by Django 5.1.6 on 2025-03-21 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_mproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mproduct',
            name='quality_inventory',
        ),
        migrations.AddField(
            model_name='mproduct',
            name='is_freesize',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mproduct',
            name='quality_inventory_of_size_L',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='mproduct',
            name='quality_inventory_of_size_M',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='mproduct',
            name='quality_inventory_of_size_S',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='mproduct',
            name='quality_inventory_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
