# Generated by Django 5.1.6 on 2025-03-25 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_remove_mproduct_quality_inventory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mproduct',
            name='color',
            field=models.CharField(default='', max_length=100),
        ),
    ]
