# Generated by Django 5.1.6 on 2025-03-26 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_mproduct_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='mproduct',
            name='display_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
