# Generated by Django 5.1.6 on 2025-03-26 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_mproduct_display_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mproduct',
            name='display_date',
        ),
    ]
