# Generated by Django 5.1.6 on 2025-03-29 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_remove_mproduct_display_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='TProductFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite_flag', models.BooleanField(default=True)),
                ('delete_flag', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.mproduct')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.muser')),
            ],
            options={
                'db_table': 't_product_favorite',
                'constraints': [models.UniqueConstraint(fields=('user', 'product'), name='unique_favorite')],
            },
        ),
    ]
