# Generated by Django 5.1.6 on 2025-04-02 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_tproductfavorite'),
    ]

    operations = [
        migrations.CreateModel(
            name='TOrderCart',
            fields=[
                ('order_cart_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=255)),
                ('product_image', models.CharField(max_length=255)),
                ('product_size', models.CharField(max_length=10)),
                ('product_quality_cart', models.PositiveIntegerField(default=1)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('delete_flag', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.mproduct')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.muser')),
            ],
            options={
                'db_table': 't_order_cart',
            },
        ),
    ]
