# Generated by Django 5.1.6 on 2025-04-22 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_tordercart'),
    ]

    operations = [
        migrations.AddField(
            model_name='tordercart',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
