# Generated by Django 5.1.6 on 2025-04-26 16:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_tordercart_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='mproducttype',
            name='create_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='mproducttype',
            name='note',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
