# Generated by Django 5.1.6 on 2025-04-26 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_mproducttype_type_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mproducttype',
            name='type_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
