# Generated by Django 5.1.6 on 2025-04-27 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_alter_mproducttype_type_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagerAccount',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('delete_flag', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'm_manager_account',
            },
        ),
        migrations.CreateModel(
            name='ManagerPassword',
            fields=[
                ('user_password_id', models.AutoField(primary_key=True, serialize=False)),
                ('password_hash', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.manageraccount')),
            ],
            options={
                'db_table': 'manager_password',
            },
        ),
    ]
