# Generated by Django 5.1.6 on 2025-04-27 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_manageraccount_managerpassword'),
    ]

    operations = [
        migrations.AddField(
            model_name='mproduct',
            name='type_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
