# Generated by Django 5.1.6 on 2025-04-27 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_mproduct_type_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='mproduct',
            name='product_code',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
