# Generated by Django 5.1.6 on 2025-04-30 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_mproduct_product_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='mproduct',
            name='quality_inventory_of_freesize',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
