# Generated by Django 5.1.6 on 2025-04-30 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_mproduct_quality_inventory_of_freesize'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mproduct',
            name='status_flag',
        ),
    ]
