# Generated by Django 5.1.6 on 2025-05-22 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_torderpayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='MMethodPayment',
            fields=[
                ('method_id', models.AutoField(primary_key=True, serialize=False)),
                ('method_name', models.CharField(max_length=100)),
                ('delete_flag', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'm_method_payment',
            },
        ),
    ]
