# Generated by Django 5.1.6 on 2025-05-22 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0021_torderwaitconfirmheader'),
    ]

    operations = [
        migrations.CreateModel(
            name='TOrderWaitConfirmDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_size', models.CharField(max_length=10)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('quality', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_product', models.CharField(max_length=100)),
                ('delete_flag', models.BooleanField(default=False)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.torderwaitconfirmheader')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.mproduct')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.mproducttype')),
            ],
            options={
                'db_table': 't_order_wait_confirm_detail',
                'unique_together': {('order', 'product', 'product_size')},
            },
        ),
    ]
