# Generated by Django 5.1.6 on 2025-05-23 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0022_torderwaitconfirmdetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='torderwaitconfirmdetail',
            name='note',
        ),
        migrations.AddField(
            model_name='torderwaitconfirmheader',
            name='note',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
