# Generated by Django 5.1.6 on 2025-10-17 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0023_remove_torderwaitconfirmdetail_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='torderwaitconfirmheader',
            name='is_new',
            field=models.BooleanField(default=True),
        ),
    ]
