# Generated by Django 5.1.6 on 2025-10-17 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0024_torderwaitconfirmheader_is_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='torderwaitconfirmheader',
            name='is_new',
        ),
    ]
