# Generated by Django 5.1.6 on 2025-10-27 17:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0025_remove_torderwaitconfirmheader_is_new'),
    ]

    operations = [
        migrations.CreateModel(
            name='TOrderHeader',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=255)),
                ('order_date', models.DateField(default=django.utils.timezone.now)),
                ('estimated_delivery_date', models.DateField()),
                ('total_price_order', models.CharField(max_length=100)),
                ('delete_flag', models.BooleanField(default=False)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_method', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.mmethodpayment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.muser')),
            ],
            options={
                'db_table': 't_order_header',
            },
        ),
    ]
