# Generated by Django 5.1.6 on 2025-10-27 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0026_torderheader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='torderheader',
            name='total_price_order',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='torderwaitconfirmdetail',
            name='price_product',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='torderwaitconfirmheader',
            name='total_price_order',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
