# Generated by Django 5.1.6 on 2025-10-27 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0027_alter_torderheader_total_price_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TOrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_size', models.CharField(max_length=10)),
                ('quality', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_product', models.DecimalField(decimal_places=2, max_digits=15)),
                ('delete_flag', models.BooleanField(default=False)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.torderheader')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.mproduct')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.mproducttype')),
            ],
            options={
                'db_table': 't_order_detail',
                'unique_together': {('order', 'product', 'product_size')},
            },
        ),
    ]
