# Generated by Django 5.1.6 on 2026-06-03 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0028_torderdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='torderheader',
            name='status',
            field=models.CharField(default='CONFIRMED', max_length=30),
        ),
    ]
