# Generated by Django 5.1.6 on 2026-06-06 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0029_torderheader_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='MStatus',
            fields=[
                ('status_id', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('status_name', models.CharField(max_length=50)),
                ('delete_flag', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'm_status',
            },
        ),
    ]
