# Generated by Django 5.1.6 on 2026-06-06 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0030_mstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='torderheader',
            name='status',
            field=models.ForeignKey(db_column='status_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.mstatus'),
        ),
    ]
