# Generated by Django 5.1.6 on 2026-06-06 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0031_alter_torderheader_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='torderheader',
            old_name='status',
            new_name='status_id',
        ),
    ]
