# Generated by Django 5.1.6 on 2026-06-06 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0032_rename_status_torderheader_status_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='torderheader',
            name='status_id',
        ),
    ]
