# Generated by Django 5.1.6 on 2026-06-06 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0033_remove_torderheader_status_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='torderheader',
            name='status',
            field=models.ForeignKey(db_column='status_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.mstatus'),
        ),
    ]
