# Generated by Django 5.1.6 on 2026-06-06 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0034_torderheader_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='TOrderStatus',
            fields=[
                ('order_status_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delete_flag', models.BooleanField(default=False)),
                ('current_status', models.ForeignKey(db_column='current_status_id', on_delete=django.db.models.deletion.CASCADE, related_name='current_status_logs', to='website.mstatus')),
                ('new_status', models.ForeignKey(db_column='new_status_id', on_delete=django.db.models.deletion.CASCADE, related_name='new_status_logs', to='website.mstatus')),
                ('order', models.ForeignKey(db_column='order_id', on_delete=django.db.models.deletion.CASCADE, to='website.torderheader')),
            ],
            options={
                'db_table': 't_order_status',
            },
        ),
    ]
