# Generated by Django 5.1.6 on 2026-06-06 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0035_torderstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='torderstatus',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
