# Generated by Django 5.1.6 on 2026-06-07 02:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0036_torderstatus_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='TOrderHistory',
            fields=[
                ('order_history_id', models.AutoField(primary_key=True, serialize=False)),
                ('current_order_size', models.CharField(max_length=20)),
                ('new_order_size', models.CharField(max_length=20)),
                ('current_quantity', models.IntegerField()),
                ('new_quantity', models.IntegerField()),
                ('current_estimate_date', models.DateField(blank=True, null=True)),
                ('new_estimate_date', models.DateField(blank=True, null=True)),
                ('delete_flag', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(db_column='order_id', on_delete=django.db.models.deletion.CASCADE, to='website.torderheader')),
                ('order_detail', models.ForeignKey(db_column='order_detail_id', on_delete=django.db.models.deletion.CASCADE, to='website.torderdetail')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='website.muser')),
            ],
            options={
                'db_table': 't_order_history',
            },
        ),
    ]
