# Generated by Django 5.1.6 on 2026-06-07 02:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0037_torderhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='THistory',
            fields=[
                ('order_history_id', models.AutoField(primary_key=True, serialize=False)),
                ('current_order_size', models.CharField(blank=True, max_length=20, null=True)),
                ('new_order_size', models.CharField(blank=True, max_length=20, null=True)),
                ('current_quantity', models.IntegerField(blank=True, null=True)),
                ('new_quantity', models.IntegerField(blank=True, null=True)),
                ('current_estimate_date', models.DateField(blank=True, null=True)),
                ('new_estimate_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delete_flag', models.BooleanField(default=False)),
                ('order', models.ForeignKey(
                    db_column='order_id',
                    on_delete=django.db.models.deletion.CASCADE,
                    to='website.torderheader'
                )),
                ('product', models.ForeignKey(
                    blank=True,
                    null=True,
                    db_column='product_id',
                    on_delete=django.db.models.deletion.CASCADE,
                    to='website.mproduct'
                )),
                ('user', models.ForeignKey(
                    db_column='user_id',
                    on_delete=django.db.models.deletion.CASCADE,
                    to='website.muser'
                )),
            ],
            options={
                'db_table': 't_history',
            },
        ),
    ]