# Generated by Django 5.1.6 on 2026-06-08 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0039_delete_torderhistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TOrderHistory',
        ),
    ]
