# Generated by Django 5.1.6 on 2026-06-08 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0040_delete_torderhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='muser',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='muser',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
